### ISSUE TITLE
Icon has a glitch on right side for the "Firefox" icon for the theme

### ISSUE THREAD

**Issue by willgk** [Godiesc/Chameleons-Beauty#1]
Please see here for an example of this, i believe it's related to 4K display, i've got it sized to 250% as i'm on a laptop.

https://imgur.com/a/1L32NLe

**Comment by Godiesc** [comment]
Thanks for the report, I couldn't see the bug in my pc, but if you want to try a solution you could edit the line 268, the rule: padding-left: 18px !important; and set it a higher number. 💙

**Comment by willgk** [comment]
Sadly no width or padding changes seem to help

**Comment by willgk** [comment]
Actually I take that back, i had some issues with firefox staying stuck in memory and looking like it was closed, so it wasn't actually taking the userChrome change. Got that all taken care of and upping it to 20px fixed it perfect! Thanks!
