### ISSUE TITLE
Right side of the search bar outline dissapears

### ISSUE THREAD

**Issue by marja21** [Godiesc/Chameleons-Beauty#10]
Thank you so much for addressing the search bar color with this version :)

A few hours ago, I added the new update to my browser. Everything was functioning properly until I noticed the right side of the popup search bar didn't have the blue outline anymore. I restarted the browser, but it still didn't show back up. Then I played around with the width of the search bar and moved it all the way to left, which fixed the outline. But after resetting the width in the settings, the same thing happened again.

![Screenshot (241)](https://github.com/Godiesc/Chameleons-Beauty/assets/108206440/9d121bd1-5e90-4c6f-9f03-24fb46e73d46)
![Screenshot (242)](https://github.com/Godiesc/Chameleons-Beauty/assets/108206440/0833eeea-1584-4a23-824d-12faa8ee6b72)

If you could investigate this, it would be much appreciated.

**Comment by Godiesc** [comment]
hi,
the theme was tested in v.119, are you using that version or beta/developer/nightly version?

**Comment by marja21** [comment]
Version 119

**Comment by Godiesc** [comment]
when I put the windows task-bar to the left or right that bug appears, maybe is a bug for differences in the width of Firefox window.

![imagen](https://github.com/Godiesc/Chameleons-Beauty/assets/22057609/44a886d8-29ce-4bdc-8b6d-1b1e5a29863a)

**Comment by Godiesc** [comment]
or if you put more/less buttons on the toolbar and the width of that search-bar changes the bug appears.

**Comment by Godiesc** [comment]
replace the lines 141 to 151 with the next code in `ch_urlbar-searchbar.css` and see if that fix the problem.

```
#PopupSearchAutoComplete {
    --uc-slot-radius: 0 0 5px 5px;
    --arrowpanel-border-radius: var(--uc-slot-radius) !important;
    background-color: var(--toolbar-field-focus-background-color) !important;
    width: calc(var(--panel-width) - 0px) !important;
    margin-top: -4px !important;
    border-radius: 0 0 5px 5px !important;
    border-left: 1px solid var(--general-color) !important;
    border-right: 1px solid var(--general-color) !important;
    border-bottom: 1px solid var(--general-color) !important;
}
```

**Comment by marja21** [comment]
I've applied your code and have been playing with the tool bar and the window size for a little bit and have yet for the bug to occur again. I'll continue to keep and eye on it, but it seems to have been fixed. Thanks for checking this out :)
