### ISSUE TITLE
Main-Image config not working

### ISSUE THREAD

**Issue by cloud-ed** [Godiesc/Chameleons-Beauty#11]
I have added a preference to about:config called "firefoxchameleon.main-image" and set it to true, but it still does not apply to browser after restarting.
![main-image-notworking](https://github.com/Godiesc/Chameleons-Beauty/assets/140370595/f17b7de3-aaf8-4362-8660-51c3534362b9)

**Comment by Godiesc** [comment]
hi, if you using beta/nightly version of Firefox it won't work; I should update the theme for new changes that will arrive with Firefox 120.
if you use Firefox v.119 be sure to update from the "[Release section](https://github.com/Godiesc/Chameleons-Beauty/releases/tag/chameleon.v3.2)".

**Comment by cloud-ed** [comment]
Thanks for the help, I must have been using an outdated version. Sorry about that
