### ISSUE TITLE
Add a dark only (and if u want white only) option for the theme "Beautiful Focused Tab"

### ISSUE THREAD

**Issue by CodeCubeNeo** [Godiesc/Chameleons-Beauty#12]
If I have my system set to light theme and want my browser to be dark theme there is no way to have the "Beautiful Focused Tab" extension work on the dark theme as it will be white (same as the system). Truly the best theme for excelent highlighting of the current active tab. But this is the one last thing missing from perfection of your work. 

Or you can also add a full color of active tab option in your GX Theme Styles extension. It is a really good implementation.
Thank you! Muchas Gracias mi amigo, muy bonito.

**Comment by Godiesc** [comment]
hi, using the chameleon's theme you can't notice the focused tab color, so I assume you are not using this css theme, and I could try to separate the white/dark themes if possible, the firefox store sometimes rejects themes that are similar or something like that.
And in 'GX Theme Styles' extension I though is more easy the change that colors in that way, I will think about add that change to the next update of the extension.

**Comment by CodeCubeNeo** [comment]
Awesome! I am talking about this> 
![image](https://github.com/Godiesc/Chameleons-Beauty/assets/61159092/258f6354-b875-4737-9d45-a8eea8dd4795)
To make this colored stand-out tab editable in your GX Theme styles + add a dark only version for this. Hope we thought the same thing.

**Comment by Godiesc** [comment]
@CodeCubeNeo The extension was updated and the themes for light and dark mode were made and are available here: https://addons.mozilla.org/es/firefox/user/7024772/?page_t=3
