### ISSUE TITLE
<option> or  bookmarks get broken.

### ISSUE THREAD

**Issue by RampyHvH** [Godiesc/Chameleons-Beauty#13]
by default any option in input will be fully white as the text inside of it gets whited because of 
` .menupopup-arrowscrollbox` 
and `menupopup>menuitem:not([disabled="true"]), menupopup>menu` _(ch_contextual-menu.css)_

even after fixing some css there there's an issue with `menupopup>menuitem:not([disabled="true"]):hover, menupopup>menu:where([_moz-menuactive]:not([disabled="true"]))`

 as on hover the text gets white 

![image](https://github.com/Godiesc/Chameleons-Beauty/assets/77925482/960a3035-07ce-4fd4-8e7c-4bd55094bf07),

 but without it the bookmarks don't get hover effect
![image](https://github.com/Godiesc/Chameleons-Beauty/assets/77925482/cc8a0b40-0c8d-457e-8193-060120ac10b7)

**Comment by Godiesc** [comment]
hi,
I would like to know the site that present that bug:

> ![image](https://private-user-images.githubusercontent.com/77925482/303469650-960a3035-07ce-4fd4-8e7c-4bd55094bf07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MjM3NzIsIm5iZiI6MTcwNzQyMzQ3MiwicGF0aCI6Ii83NzkyNTQ4Mi8zMDM0Njk2NTAtOTYwYTMwMzUtMDdjZS00ZmQ0LThlN2MtNGJkNTUwOTRiZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDIwMTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjY2VjNzQ3NWU5ZDlmZDgzODQ1NjZjNGU0NzZjYmI0OTFmY2Q3NjU4NmExMzdiYWI1Mzk4NmZjNDJiNGZhZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vKpz4T0_eREaa0F1083-RNQCltMGIGonGMDA8-uwric),

and what theme are you using in about:addons page, I shared some compatible themes, aren't you using them?

**Comment by RampyHvH** [comment]
> about:addons
![image](https://github.com/Godiesc/Chameleons-Beauty/assets/77925482/7d2db2d9-13e8-471a-aca9-f42ba184ae90)


and for the site is basically every site with vanilla <option> tag

if you really wwant to check. here's the [site](https://floppa.cc/unit-converter/)

**Comment by Godiesc** [comment]
I updated the file [ch_contextual-menu.css](https://github.com/Godiesc/Chameleons-Beauty/blob/main/chrome/components/ch_contextual-menu.css) to solve the problem, if other problem appears please report it.

**Comment by RampyHvH** [comment]
![image](https://github.com/Godiesc/Chameleons-Beauty/assets/77925482/046416a9-b8d3-44bb-a91e-5446221715cc)
similar glitch but now after hovering and replacing your mouse it becomes white, and while switching from one option to another it also flicks white, probably somewhere still getting changed back.

**Comment by Godiesc** [comment]
pls update the file again and test it again, I updated other code in that file just a few seconds ago.

**Comment by RampyHvH** [comment]
seems to be fixed, thanks!
