### ISSUE TITLE
Organize, Views, Import and Backup missing from Bookmarks Manager toolbar

### ISSUE THREAD

**Issue by kartana** [Godiesc/Chameleons-Beauty#16]
Those options aren't there with this CSS theme.

**Comment by Godiesc** [comment]
hi, I don't know what you mean, this is a css theme and didn't hide any element, what do you mean with: organize, views...? A screenshot should clarify me the issue.

**Comment by kartana** [comment]
This part with the menu is missing if I apply your CSS files.

![Screenshot 2024-04-20 085815](https://github.com/Godiesc/Chameleons-Beauty/assets/8889810/c7f42592-57cd-4387-bb80-249ec69cb5c4)

**Comment by Godiesc** [comment]
thanks for the report, I updated the file: [ch_tabs-bar.css](https://github.com/Godiesc/Chameleons-Beauty/blob/main/chrome/components/ch_tabs-bar.css) to solve the problem, if you descover other issue in the future Don't hesitate to report it.
