### ISSUE TITLE
Some simple questions

### ISSUE THREAD

**Issue by CrazyWolf13** [Godiesc/Chameleons-Beauty#17]
Hi

Really really awesome thing you wrote here!!!!
Love it!

A bit sade that the code comments are mostly spanish, but I oculd mostly change what I wanted to adapt for me.

But now I've got some questions,

1. How do I change the color of the active tab?
![grafik](https://github.com/Godiesc/Chameleons-Beauty/assets/96661824/7e541baf-47e6-4953-aa6a-a94f7209bbcc)
I'd like the default to be a shade of green similar to "Beautiful GX Green" but I use "Beautiful GX Proton" with userChome, I literally changed every single blue color var to be green and that thing is still blue 🙄.

2. How do I change the color of the first google search result?
![grafik](https://github.com/Godiesc/Chameleons-Beauty/assets/96661824/14470df3-13c0-4dea-8b21-8fcccb33a747)

3. How may I change the thickness of  the searchbar?
![grafik](https://github.com/Godiesc/Chameleons-Beauty/assets/96661824/77c2b35f-f5a0-4d35-8dfb-1ad30bdc2361)

The other things I could find out myself.

Huge thanks for this awesome theme!

**Comment by Godiesc** [comment]
Hi,
> 1. How do I change the color of the active tab?

that color is taken from the theme "Beautiful GX Proton" and you can change it with the variable in the css of the extension, I guess you are using the code for Tab-center-reborn:

`--identity-color: #ff0000;`

![imagen](https://github.com/Godiesc/Chameleons-Beauty/assets/22057609/0ad50659-48f2-47ad-8e6d-1a4e9d2a69b9)

you can change too with my extension: [GX-theme-styles](https://addons.mozilla.org/es/firefox/addon/gx-theme-styles/) and the color for **Accent color**.


> 2\. How do I change the color of the first google search result?

the theme display a gradient background and if you have just blue I guess you edited the file `ch_urlbar-searchbar.css` line 34, but with the next code you delete the gradient and add the color you want:

```
.urlbarView-row:not([type="tip"], [type="dynamic"])[selected] > .urlbarView-row-inner, .urlbarView-row-inner[selected] {
    background-image: none !important;
    background-color: #10af20 !important;
}
```

> 3\. How may I change the thickness of  the searchbar?

if you mean all the toolbar height you have the option in `ch_root_personal.css` line 34.
if you want to change the urlbar height you can change that in the `ch_urlbar-searchbar.css` file line 101-103 with a bigger number:

![imagen](https://github.com/Godiesc/Chameleons-Beauty/assets/22057609/9296820c-b639-485c-a2fc-a6b527b2bbcd)

**Comment by CrazyWolf13** [comment]
Huuge thanks!!
And even thant quick 😊

Got both 1 and 2 to work.

With 3 I actually meant the borderline, make the borderline a bit thicker. 
I tried with adding a border property, but that broke on selected function, so it has a different color when it's selected.
![grafik](https://github.com/Godiesc/Chameleons-Beauty/assets/96661824/733b1214-c5a0-4353-ab3e-ae8edb932ee7)

**Comment by Godiesc** [comment]
you can use this code to get 2px and the color you want too:

```
#urlbar-background, #searchbar {
  border: 2px solid var(--toolbar-field-border-color) !important;
}
```

**Comment by CrazyWolf13** [comment]
Thanks!

Worked wonders :)
