### ISSUE TITLE
broken buttons in the new update (v 133.0 main channel)

### ISSUE THREAD

**Issue by robinix** [Godiesc/Chameleons-Beauty#18]
i have sidebar enabled and since the update (133.0) reload, back and forward buttons look like this , would appreciate it if it was fixed. love this theme :)
![Screenshot 2024-11-26 183836](https://github.com/user-attachments/assets/cad9bad2-27a1-457e-9065-020f1307198d)

**Comment by robinix** [comment]
also broken for minimized window
![image](https://github.com/user-attachments/assets/abf70174-44c4-4e9f-934f-4ce102755a39)

**Comment by Godiesc** [comment]
hi,
thank for the report, Firefox is changing a lot of things for the future features, I will check soon the issues for this theme.

**Comment by Godiesc** [comment]
hi again,
I updated some files to solve issues for Firefox 133, please, test it and report any issue you find.

**Comment by robinix** [comment]
@Godiesc  Can confirm it's now working as intended, Thank you for the fix and have a great day :)
