### ISSUE TITLE
My container tabs do not look like the ones from the screenshots

### ISSUE THREAD

**Issue by thecursehunter** [Godiesc/Chameleons-Beauty#2]
![image](https://user-images.githubusercontent.com/73272262/160110464-8f5dfa5c-1276-4ec1-870e-9d41b2a8650a.png)

Desktop:
- OS: Windows: 10 Pro 64-bit (10.0, Build 19044) (19041.vb_release.191206-1406)
- Firefox version: 98.0.2

**Comment by Godiesc** [comment]
hi, Could you tell me what extension of containers are you using, and give me a SS to the all the browser to verify the tab is in a container.

**Comment by thecursehunter** [comment]
> 

I need a container extension? Because I thought that the container tabs feature would work if I only pinned the tabs.

**Comment by Godiesc** [comment]
It doesnt work that way, you need the extension for that, one example is [Facebook Container](https://addons.mozilla.org/es/firefox/addon/facebook-container/) or the [Firefox Multi Account Container](https://addons.mozilla.org/es/firefox/addon/multi-account-containers/) extension.

**Comment by thecursehunter** [comment]
> 

thanks for the help
