### ISSUE TITLE
Thickness of the bookmark folder border

### ISSUE THREAD

**Issue by kartana** [Godiesc/Chameleons-Beauty#3]
Love this theme but I find the thickness of the bookmark folder border kinda ridiculous in the last update. Can you point me to the setting where I can make it as thin as around the settings/hamburger window? Thanks

[https://i.imgur.com/Naw5F7Y.png](url)

**Comment by Godiesc** [comment]
Hi, that is a bug that right now I don't know how to fix, I hope to solve in a near future, thanks for reporting.

**Comment by Godiesc** [comment]
hi again,
The problem was solved and now has 1px gradient border.
