### ISSUE TITLE
Scroll Wheel looks... weird.

### ISSUE THREAD

**Issue by VespaWoman21** [Godiesc/Chameleons-Beauty#4]
Well, my problem is that when I use the scroll wheel, the graphics look all weird. How do I fix this? Thanks. (Embeded image related) 
![image](https://user-images.githubusercontent.com/89706395/164999440-4136c822-b800-4442-8fee-683b6170784f.png)

**Comment by Godiesc** [comment]
Hi again, the bug was fixed in the latest update, thanks for report it, I appreciate it.
