### ISSUE TITLE
Home icon is not completely centered

### ISSUE THREAD

**Issue by danielyor** [Godiesc/Chameleons-Beauty#5]
This is a very small issue but I can't unsee it now that I've noticed it!

Screenshots from the UI and with dev tools inspect on home.svg
![ff-home-1](https://user-images.githubusercontent.com/22645152/169998753-fafbc731-6c23-4e49-a948-b859c122d56a.png)
![ff-home-2](https://user-images.githubusercontent.com/22645152/169998759-90e4763d-10a9-49e9-bba0-b52f4b6f9bad.png)

**Comment by Godiesc** [comment]
Hi, I noticed that too in the default theme of firefox, and I noticed that even if the icon is not centered itself it is align(horizontal) with the rest of the toolbar icons. You think is needed a vertical align (itself) or in the total middle?  that will cause a non align with the rest of the icons jeje.

**Comment by danielyor** [comment]
Yes, I meant that its horizontal alignment wasn't in the center of its button! I should've been more clear about that.

I applied your new .svg and the issue is now fixed. Thanks! 😁
