### ISSUE TITLE
Gradient not being applied

### ISSUE THREAD

**Issue by eunomicZenith** [Godiesc/Chameleons-Beauty#6]
Hello! I recently got this theme, but the beautiful gradient that, for example, the active tab should have, isn't there.

I'm pretty sure I have correctly installed Chameleon's Beauty - I have customized the wallpaper of my new tab using it, also, so that's proof that it works.
I also have installed and enabled the Beautiful GX Proton theme.

What am I doing wrong? Why is there no gradient?

<img width="803" alt="Screenshot_3" src="https://user-images.githubusercontent.com/31997989/194765418-568f3169-d641-475f-8d32-a56649c41a13.png">

**Comment by Godiesc** [comment]
hi,
I tested right now the theme and works fine. Is rare that you can edit the new tab but the rest of the theme don't work. make sure you have all the files into chrome -> "components" folder, maybe for some reason you don't pasted them.

**Comment by eunomicZenith** [comment]
<img width="583" alt="Screenshot_6" src="https://user-images.githubusercontent.com/31997989/194774553-fc8b6ca9-bb09-4bf3-b126-902ee929ad23.png">
<img width="583" alt="Screenshot_5" src="https://user-images.githubusercontent.com/31997989/194774398-b6965368-a7ed-4e75-9701-97b3448c9b35.png">

No, the "components" folder is definitely there, as you can see (and I haven't edited its contents at all, I only copy-pasted them).
I do have a couple of other small things in my userChrome.css file, but as far as I know, they shouldn't be causing problems. You can take a look [here](https://pastebin.com/G9vgSzqX) if you want. The stuff from Chameleon's Beauty is at the bottom.
The userContent.css file, on the other hand, has only been copypasted and only contains Chameleon's Beauty two lines of code.

**Comment by Godiesc** [comment]
that's the problem mate, all the imports needs to be on top of the file, and after that you ca put other codes.

**Comment by eunomicZenith** [comment]
![image](https://user-images.githubusercontent.com/31997989/194774994-5698b99f-7245-47d2-9ad2-6c94551c6d70.png)

Thank you! I had no idea they needed to be at the top, I only got Firefox two days ago. Sorry for bothering you :)

**Comment by Godiesc** [comment]
no problem, if you get other problem don't doubt to contact me like this time. 💙
