### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by roaminghawk** [Godiesc/Chameleons-Beauty#7]
Hi,

Will you update this theme or are you more focused on your new theme?

**Comment by Godiesc** [comment]
hi,
I usually update the themes when bugs appear. If you find one you can fill an issue report like this, and I will fixed, but if you like other features you can suggest to me if I can do it I will do.

**Comment by roaminghawk** [comment]
Thanks for the reply.

Currently there is only one bug introduced with FF 113 as far as I can see.
Boxes from menus and folders have like a shodow, I don't think that is it intentional since it was not there before FF113.

[https://i.imgur.com/b9GXD2M.png](url)
[https://i.imgur.com/mHCIK14.png](url)

**Comment by Godiesc** [comment]
I tested just now the theme and other issue is in the urlbar open. you have this issue too, I guess.

In a few hours or minutes I will try to fix the issues, if you find out other issue pls report them, I will appreciate the help.

**Comment by roaminghawk** [comment]
Actually the urlbar is fine, there is a small flash when it opens, but no shadow. 
https://i.imgur.com/9zurMy8.png

Take all the time you need. I will continue reporting any more bugs I find in the future. And Thank you very much for your theme, support and attitude.

**Comment by Godiesc** [comment]
![imagen](https://github.com/Godiesc/Chameleons-Beauty/assets/22057609/f73fd69c-59a3-4982-9853-0393b878d000)
 I have an issue with the urbbar open, I wonder why you dont have it.

**Comment by roaminghawk** [comment]
Now that I see those transparent entries in the urlbar, I remember with FF 112 those transparent entries started to appear, and I didn't like them. So I started removing parts of the code until I solved it.

**Comment by roaminghawk** [comment]
components\ch_urlbar-searchbar.css
The part I removed:
`
#urlbar {
    min-height: 26px !important;
    border-radius: 4px !important;
    max-height: 26px !important;
}`

**Comment by Godiesc** [comment]
thanks, I hope solve all the problems soon. Await for the theme updated. ❤

**Comment by Godiesc** [comment]
I updated the theme, for now seems to be all fixed. if you find out another, pls report. Thanks. ❤

**Comment by roaminghawk** [comment]
All is indeed fixed. Thanks again
