### ISSUE TITLE
FF117 Black Icons

### ISSUE THREAD

**Issue by roaminghawk** [Godiesc/Chameleons-Beauty#8]
Hi,

With FF117, some icons are black, so in a dark seem they are invisible.
1-Back and security:
![image](https://github.com/Godiesc/Chameleons-Beauty/assets/24497065/72d92391-7ab7-4eed-abb8-a83a1c96d5a1)
2- Open application menu:
![image](https://github.com/Godiesc/Chameleons-Beauty/assets/24497065/f63219b1-4231-49ea-b65a-82501b6774f6)
3- Add to bookmarks icon:
![image](https://github.com/Godiesc/Chameleons-Beauty/assets/24497065/9b89806c-3fb2-46bc-aacc-dc51b7c4c321)

Also there is a bug from earlier versions, in the Library/Bookmarks window, selecting text from the name or the tags of selected bookmark does not have a highlight, while selecting URL or keywords have a highlight:
![image](https://github.com/Godiesc/Chameleons-Beauty/assets/24497065/a98720fa-d1de-4b4e-b353-d2b0a5b5568e)

Thank you.

**Comment by Godiesc** [comment]
hi, thanks for the report, I don't present that issues, maybe you are not using the `[user.js](https://github.com/Godiesc/Chameleons-Beauty/blob/main/user.js)` file, plspaste that file in your profile folder and let me know if that fixes your problems, I Updated some files to fix other problems (window controls and URL vertical align).

> Also there is a bug from earlier versions, in the Library/Bookmarks window, selecting text from the name or the tags of selected bookmark does not have a highlight, while selecting URL or keywords have a highlight:

this works fine cause that is the proper function, you can't select the name or change the tabs manually writing, if you want to do that you need to open that page and with the "bookmark" button in the urlbar you change easily.
You can test that with other theme or without theme and works the same, if not let me know.

**Comment by roaminghawk** [comment]
Thanks for the update.
I have user.js in place and is identical to the one in the link.
Removing ch_toolbar-icons.css solves the problem for me. I think it's some to do with the images folder. If you can't replicate the issue there is no problem.
Library is fixed and I've updated the other files you mentioned as well.

Thanks again.

**Comment by Godiesc** [comment]
be sure you have this in true, if not you pasted the user.js file on the wrong folder.
![imagen](https://github.com/Godiesc/Chameleons-Beauty/assets/22057609/8b357384-8cf5-4b4e-9010-0a32584484f1)

**Comment by roaminghawk** [comment]
That solved it.

Thanks again.
