### ISSUE TITLE
Rainbow effect isn't applied to the search bar when active

### ISSUE THREAD

**Issue by marja21** [Godiesc/Chameleons-Beauty#9]
![Screenshot (232)](https://github.com/Godiesc/Chameleons-Beauty/assets/108206440/cbeffd74-ab83-4666-8766-8be2264687b0)
The border around the search bar doesn't have the blue and purple gradient...

![Screenshot (231)](https://github.com/Godiesc/Chameleons-Beauty/assets/108206440/71714bf1-f7e3-4373-ad2c-9948248a81b6)
Like the URL address bar does.

**Comment by Godiesc** [comment]
hi,
the rainbow effect is not set in the search-box because they are two elements (search-box and drop-down) and for me is impossible to make a rainbow border like in the address bar.

**Comment by marja21** [comment]
Ah, I see. Well that's a shame, but great theme regardless.
